# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: netconsd.spec
files_to_sync:
  - netconsd.spec
  - .packit.yaml

upstream_package_name: netconsd
downstream_package_name: netconsd
actions:
  # Fetch the specfile from Rawhide and drop any patches
  post-upstream-clone: "bash -c \"curl -s https://src.fedoraproject.org/rpms/netconsd/raw/main/f/netconsd.spec | sed '/^Patch[0-9]/d' > netconsd.spec\""

jobs:
- job: copr_build
  trigger: commit
  metadata:
    owner: "@meta"
    project: netconsd
    targets:
      - fedora-all-aarch64
      - fedora-all-armhfp
      - fedora-all-i386
      - fedora-all-ppc64le
      - fedora-all-s390x
      - fedora-all-x86_64
      - fedora-eln-aarch64
      - fedora-eln-i386
      - fedora-eln-ppc64le
      - fedora-eln-s390x
      - fedora-eln-x86_64
      - epel-8-aarch64
      - epel-8-ppc64le
      - epel-8-s390x
      - epel-8-x86_64
      - epel-9-aarch64
      - epel-9-ppc64le
      - epel-9-s390x
      - epel-9-x86_64
- job: copr_build
  trigger: pull_request
  metadata:
    owner: "@meta"
    project: netconsd
    targets:
      - fedora-all-aarch64
      - fedora-all-armhfp
      - fedora-all-i386
      - fedora-all-ppc64le
      - fedora-all-s390x
      - fedora-all-x86_64
      - fedora-eln-aarch64
      - fedora-eln-i386
      - fedora-eln-ppc64le
      - fedora-eln-s390x
      - fedora-eln-x86_64
      - epel-8-aarch64
      - epel-8-ppc64le
      - epel-8-s390x
      - epel-8-x86_64
      - epel-9-aarch64
      - epel-9-ppc64le
      - epel-9-s390x
      - epel-9-x86_64
